FROM node:14-alpine as node

WORKDIR /app

COPY package-lock.json .
COPY package.json .

RUN npm install

COPY . .

# Copy .env.staging to .env BEFORE build
RUN cp .env.staging .env

RUN npm run build


FROM nginx:stable-alpine as frontend_server

COPY --from=node /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]