apiVersion: apps/v1
kind: Deployment
metadata:
  name: superadmin-frontend
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: superadmin-frontend
  template:
    metadata:
      labels:
        app: superadmin-frontend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: superadmin-frontend  
          image: 834033184010.dkr.ecr.ap-southeast-2.amazonaws.com/alija-frontend-k8s:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
   
          volumeMounts:
            - mountPath: /data/storage
              name: superadmin-volume
      volumes:
        - name: superadmin-volume
          hostPath:
            path: /data
            type: DirectoryOrCreate
