apiVersion: v1
kind: PersistentVolume
metadata:
  name: superadmin-pv
  namespace: frontend
spec:
  capacity:
    storage: 1Gi  # Adjust as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: pgadmin-storage
  hostPath:
    path: /mnt/data/pgadmin # This is the host path where session data will be stored
    type: DirectoryOrCreate