apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superadmin-pvc
  namespace: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: pgadmin-storage