apiVersion: v1
kind: Service
metadata:
  name: superadmin-frontend
  namespace: frontend
spec:
  type: NodePort
  selector:
    app: superadmin-frontend
  ports:
    - port: 82
      targetPort: 80
      nodePort: 30002
      protocol: TCP

